title: Anmol Swain
logo: /assets/img/assets/img/296404509_472484904277143_4310472620260846512_n.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
